### ISSUE TITLE
[Feat]: Mobile responsive

### ISSUE THREAD

**Issue by subrat611** [dakshsinghrathore/ISRO-web#1]
Hii @dakshsinghrathore I want to make this site responsive, could you assign this to me.

![Screenshot_2023-10-02-09-04-12-17_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/dakshsinghrathore/ISRO-web/assets/77252075/abfbcf0b-b17c-42dc-943f-d7b4e813f632)

**Comment by dakshsinghrathore** [comment]
Assigned it to you🤝

**Comment by subrat611** [comment]
@dakshsinghrathore Could I rewrite the css files from scratch?
The design must be same as per the previous one.

**Comment by dakshsinghrathore** [comment]
@subrat611 yeah sure, just keep in mind the design flow must be intact !

**Comment by subrat611** [comment]
Sure

**Comment by Pinaka-Pani-18** [comment]
Hi @dakshsinghrathore Can I work on this issue ?

**Comment by dakshsinghrathore** [comment]
@subrat611 any updates ??

**Comment by dakshsinghrathore** [comment]
> Hi @dakshsinghrathore Can I work on this issue ?

yeah you can work on this issue too!

**Comment by Abishkardhenga** [comment]
@dakshsinghrathore  hey i think they are not  working on this issue can you assign it to me . I will solve it asap

**Comment by dakshsinghrathore** [comment]
@Abishkardhenga assigned !!

**Comment by dakshsinghrathore** [comment]
@Abishkardhenga any updates ??

**Comment by tusharshah21** [comment]
Hey, can you assign it to me?

**Comment by tusharshah21** [comment]
@dakshsinghrathore PR sent yesterday; could you please review it!

**Comment by tusharshah21** [comment]
@dakshsinghrathore can you please close the issue now if it is fixed?
