### ISSUE TITLE
Feat: Update readme.md

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#104]
### Describe the feature

Generate an image of contributors to keep README.md in sync. 
Kindly refer to [this](https://contrib.rocks/preview?repo=angular%2Fangular-ja)

### Add ScreenShots

**SOMETHING LIKE THIS 👇🏽**

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/c46b9cd7-4a17-40cb-b20c-0b53db05572d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by rohits-web03** [comment]
#### I would like to work on this

**Comment by dakshsinghrathore** [comment]
@rohits-web03 assigned, happy coding 😀🤝

**Comment by rohits-web03** [comment]
#### Would you like to mention it in the readme that it was made using contrib.rocks along with the link to their wbesite?

**Comment by dakshsinghrathore** [comment]
@rohits-web03 no !

**Comment by rohits-web03** [comment]
#### Ok
#### Is this fine?
![README.md contributors](https://github.com/dakshsinghrathore/ISRO-web/assets/132741672/7e99bc04-a4ec-4dc2-a7b8-13ac107c0982)
