### ISSUE TITLE
BUG: Update twitter icon

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently the logo of this twitter is outdated, kindly update it with the latest X one in the footer section, here is the [link](https://fontawesome.com/icons/x-twitter?f=brands&s=solid)

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/c3c09938-a01a-4407-872f-6e0ec69e643b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by Somil-Shukla** [comment]
assign this issue to me
