### ISSUE TITLE
Feat: Update Image Gallery

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#109]
### Describe the feature

Kindly add the images of Gaganyan mission ! try to keep the quality as high as possible 

### Add ScreenShots

![gag](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/5bcc142a-f8a9-4ab0-88ad-5245615e84e8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by rituraj12797** [comment]
assign this issue to me and kindly give more infr where do you wnat the image to be on tha page

**Comment by dakshsinghrathore** [comment]
There is already a Image section you just need to add more Images with Gaganyan misson title and respective images in it !
