### ISSUE TITLE
BUG: ISRO logo in images page

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On clicking ISRO logo in the images page, its reloading instead of heading to Home page !

[screen-recorder-sat-oct-21-2023-13-11-00.webm](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/74605901-1600-4dbf-b348-ecc8d4a86400)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by rituraj12797** [comment]
i would like to wor on this issue kindly assign it to me

**Comment by 08Uzair** [comment]
Please assign this to me

**Comment by shubhusion** [comment]
@dakshsinghrathore kindly assign this to me. Bug Rectified. Waiting for your confirmation to do the PR.

**Comment by dakshsinghrathore** [comment]
> I will make the PULL REQUEST as soon as u assigned me the issue

@08Uzair Thanks for choosing the issue, assigning you the issue straight away....... it would be lovely if dropped a star and follow on this repo and my profile respectfully ! Happy Coding .🤝

**Comment by dakshsinghrathore** [comment]
@shubhusion I highly appreciate your quick response, but this is not a good practice of raising a PR without even getting a green flag on working on it from the admin ! Kindly follow the best practices ✨ Merging the PR 🤝
