### ISSUE TITLE
BUG: Scroll to top button

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Scroll to top button not working !!

[screen-recorder-tue-oct-24-2023-17-36-06.webm](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/96c6a790-471e-47cb-9fe5-252cd2b53998)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@Shubhangam333 assigning it to you, kindly drop a star on this repo and a follow on this acc will be much appreciated !!

**Comment by PrathameshSonje** [comment]
Hey, can I also work on this issue ?

**Comment by PrathameshSonje** [comment]
Please let me know for any changes

**Comment by AdityaGaur7** [comment]
kindly assign me this i wanna work for it

**Comment by Shashankpantiitbhilai** [comment]
Kindly assign it to me
