### ISSUE TITLE
BUG: Padding issue

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Kindly adjust the padding of the respective hamburger buttons !

[screen-recorder-wed-oct-25-2023-10-23-19.webm](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/16a167f7-efc8-44d3-a65f-9116b3b51197)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by priyanka-s12** [comment]
Can you elaborate more on this issue ?

**Comment by auth-02** [comment]
@dakshsinghrathore can you assign this to me?
