### ISSUE TITLE
Feat: Update Image

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#129]
### Describe the feature

Update the image of the hiring page to a more apt as well as high quality one !

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/c5e3672c-16ef-4c04-8443-708bed3b8708)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by priyanka-s12** [comment]
Hi, I want to work on this issue..

**Comment by dakshsinghrathore** [comment]
@priyanka-s12 Sure go ahead, kindly star the repo and a follow on this would be much appreciated !
