### ISSUE TITLE
DOC: Update the hacktoberfest banner

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#133]
### What's wrong with the existing documentation

Currently the banner of hacktoberfest is not visually pleasing for light mode github users in readme.md file .... use [this ](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/b9ea6686-038d-49cb-a4e5-8045971dbbd7) instead !

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/1f550528-0873-46dc-ad26-94fbf92c1757)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by AdityaGaur7** [comment]
please assign this to me , I would like to fix this issue at the earliest

**Comment by dakshsinghrathore** [comment]
@AdityaGaur7  assigned!

**Comment by Shashankpantiitbhilai** [comment]
assign this to me please
