### ISSUE TITLE
Feat: Update Suppliers button

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#136]
### Describe the feature

Create a HTML page regarding the suppliers of ISRO, reference this [website ](https://blog.aerospacenerd.com/p/isro-partners)
and link it to the button present in the footer.

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/be671fe0-d612-4671-9779-a358c9b57c08)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by Pariharx7** [comment]
Hello 

I want to work on this issue. 

Can you please elaborate the issue and assign it to me.

**Comment by dakshsinghrathore** [comment]
@Pariharx7 create something similar to this https://blog.aerospacenerd.com/p/isro-partners and link it with the suppliers button

**Comment by Pariharx7** [comment]
Ok 👍

**Comment by Jatingupta9120** [comment]
Bhai mai begiiner hun smj ni aya mujhe Krna kya h jo reference dia h waisa html page bnana h aur usko suplier Wale button p jb click kre to mera html page khule? Aisa kuch?

**Comment by Pariharx7** [comment]
Yes bro

I'm also beginner in Web Dev, I understood what the owner wants and now I'm working on it.

**Comment by Jatingupta9120** [comment]
> Yes bro
> 
> I'm also beginner in Web Dev, I understood what the owner wants and now I'm working on it. 

Bhai Maine Jo bola wo shi hai?
