### ISSUE TITLE
DOC: Update README.md

### ISSUE THREAD

**Issue by apu52** [dakshsinghrathore/ISRO-web#137]
### What's wrong with the existing documentation

Hello ,
I want to add some of the good looking API boxes to this repo that will help you & also the other Contributors to take a track of your repo like
- GitHub repo visitors
- Github Stars
- Github Closed & open issues/PR
- Github Last commit
- Github Repo size

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/114172928/72bb85ea-4624-4e7e-b090-65c3ee643393)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by apu52** [comment]
@dakshsinghrathore Please assign me this issue under OSEN

**Comment by dakshsinghrathore** [comment]
@apu52  assigned

**Comment by weshaan** [comment]
@apu52 hey, are you still working on this?

**Comment by apu52** [comment]
> @apu52 hey, are you still working on this?

I have already worked with this issue & my PR is already merged
