### ISSUE TITLE
BUG: Arrow adjustment 

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Arrow popping up in the red box isn't at its correct position, kindly fix the position and bring it to the green center. 

![Screenshot 2023-11-12 105323](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/752bbae6-d633-484f-b720-a8f774d9416c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by masterghost2002** [comment]
## Fix suggestion for those who want to work
1. Remove the arrow from the inner section and place it into the main section div (main section is position relative).
2. Apply bottom css, left 50%, right 50% on the arrow div (position absolute).
3. Repeat the whole process for all the sections

**Comment by rishabh-patil-03** [comment]
Is this issue available? I am new to open source I would love to contribute

**Comment by rishabh-patil-03** [comment]
Can you please guide me? @dakshsinghrathore

**Comment by rishabh-patil-03** [comment]
Hey @dakshsinghrathore I have made these changes kindly check and your feedback is appreciated

**Comment by tusharshah21** [comment]
@dakshsinghrathore if not completed uptill now assign it to me please!
