### ISSUE TITLE
BUG: BG Image, Typo, Buttons

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Change the background image of this Feedback Page and make the button have cursor:  pointer effect in it along with the typo "Slect"

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/4d2a754d-f447-4b4b-8dea-8ffd8c0d6999)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by nitishpratap** [comment]
i want to contribute to this issue.
kindly assign this to me

**Comment by dakshsinghrathore** [comment]
Assigned @nitishpratap kindly star the repo and a follow will be much appreciated 😃

**Comment by nitishpratap** [comment]
Fixed the issue in this pr
https://github.com/dakshsinghrathore/ISRO-web/pull/145
