### ISSUE TITLE
BUG: Hamburger button

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Fix the alignment of the hamburger button with nav-items**

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/7a76ca6b-6cec-4029-a874-d9795186aaf8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by tusharshah21** [comment]
@dakshsinghrathore assign it to me

**Comment by tusharshah21** [comment]
@dakshsinghrathore please look into the PR and close the issue if it is completed
