### ISSUE TITLE
Feat: Update Scroll Up

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#147]
### Describe the feature

**Make the background transparent of the arrow button which pops up on scrolling down, & border color orange**

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/e6917e46-6698-4fe5-9d23-1d8b0c55d8a0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by Achal-00** [comment]
Hey, I would like to work on this.

**Comment by dakshsinghrathore** [comment]
Hey  @Achal-00 assigned this issue to you, it would be lovely if you kindly drop a star on this repo 😃
