### ISSUE TITLE
Feat: Contact button on every page

### ISSUE THREAD

**Issue by vishalkj2002** [dakshsinghrathore/ISRO-web#152]
### Describe the feature

Currently, the Contact Us button is only showing on home page of the site, and not on the other pages.

### Add ScreenShots

Home Page
![Screenshot 2023-11-17 090756](https://github.com/dakshsinghrathore/ISRO-web/assets/117644795/5a80701d-c816-44a8-a0c3-7c2ed402714a)

Other Page
![Screenshot 2023-11-17 090825](https://github.com/dakshsinghrathore/ISRO-web/assets/117644795/ce6d3b20-5dc1-4e0c-9dd3-3ca7c078402a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@vishalkj2002 Kindly check the deployment it is already there.

**Comment by vishalkj2002** [comment]
Oh sorry!

**Comment by dakshsinghrathore** [comment]
@vishalkj2002 no need to be sorry, you can contribute by fixing new issues, which I will be creating shortly.... kindly check the issues frequently and also please don't forget to star the repo. 😃
