### ISSUE TITLE
add 2 new dedicated page for 2 navbar

### ISSUE THREAD

**Issue by Soumya-9641** [dakshsinghrathore/ISRO-web#17]
![Screenshot 2023-10-04 232615](https://github.com/dakshsinghrathore/ISRO-web/assets/98831819/f926f107-5436-4783-aca2-14ebcbbc8d7d)
Want to create dedicated page for last 2 navbar because it shows same page content as index.html.

**Comment by dakshsinghrathore** [comment]
Communication Satellites page has already been done [https://dsr-isrowebapp.netlify.app/commu]
, you can go ahead with the foreign one !!

**Comment by Soumya-9641** [comment]
Ok I will do @dakshsinghrathore
