### ISSUE TITLE
[FEAT]: Create a career page 

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#18]
## Create a careers page where you can find **up-to-date job postings** for both ISRO and SpaceX .

The career button should redirect you to a new HTML page where the job postings are mentioned

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/253c895d-a145-4a6e-b885-e23a87ca5d17)

### Kindly keep the design flow of the careers page as similar as possible to all the other pages

**Comment by Soumya-9641** [comment]
Assign me.I will do it.
