### ISSUE TITLE
[FEAT]: Create issue buttons

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#2]
Currently the contributor has to raise an issue from ground zero without any ***prebuilt buttons***, to gain a better understanding of the issue raised we can create custom issue buttons which will be ***visually appealing*** as well ***hassle free*** for the contributor to express their concern in an ***ordered manner*** .
 Here 👇 are some screenshots attached to give you a better understanding on what am up to
### Currently 

![Screenshot 2023-06-13 at 23-14-43 New Issue · SrijanShovit_carbonops-v2](https://github.com/SrijanShovit/carbonops-v2/assets/115932772/66a1f488-b745-4124-a218-92bbbc7307ef)

### To Come

![Screenshot 2023-06-13 at 23-19-39 New Issue · priyankarpal_ProjectsHut](https://github.com/SrijanShovit/carbonops-v2/assets/115932772/42addc33-f9fb-4eaf-b60a-fb7dab74844c)

**Comment by the-amazing-atharva** [comment]
I would like to work on this for hacktoberfest
