### ISSUE TITLE
[FEAT] : Add Web Pages to Footer Section Options

### ISSUE THREAD

**Issue by anuragverma108** [dakshsinghrathore/ISRO-web#24]
Hello @dakshsinghrathore ,

I hope this message finds you well. I am reaching out to request a new feature addition to the repository.

Feature Request:
I would like to incorporate the ability to link web pages to the footer section options. Specifically, I plan to create two new web pages: a "Privacy Policy of ISRO" page and a "Supplier Section" page.

Details:

Privacy Policy of ISRO Web Page
Supplier Section Web Page
Sample Look : 
![Screenshot (135)](https://github.com/dakshsinghrathore/ISRO-web/assets/129655645/917114a9-b2d8-4270-93b4-acdc89901c78)
![Screenshot (136)](https://github.com/dakshsinghrathore/ISRO-web/assets/129655645/1625ec2c-11a5-4129-8e28-500970135cb4)

Could you please assign this feature request to me? I'm eager to get started on implementing this enhancement.
Thank you for considering this request. Looking forward to your feedback.

**Comment by dakshsinghrathore** [comment]
assigned !

**Comment by dakshsinghrathore** [comment]
@anuragverma108 any updates ??

**Comment by anuragverma108** [comment]
working on it @dakshsinghrathore . I'll update soon,

**Comment by anuragverma108** [comment]
![Screenshot (137)](https://github.com/dakshsinghrathore/ISRO-web/assets/129655645/c0620b5f-4162-4794-b414-f8151704e19a)
Working !!!!

**Comment by anuragverma108** [comment]
@dakshsinghrathore. Added Privacy web page. I've also created PR to add it. Please review it.
