### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by hollermay** [dakshsinghrathore/ISRO-web#25]
It would be great if I could add a subscribe to newsletter feature which could actually send monthly newsletter to the subscribers. Will you assign this to me?

**Comment by dakshsinghrathore** [comment]
Could you please provide more details about the specific location or context where this feature will be implemented?

**Comment by hollermay** [comment]
I see my implementation in two ways:
1. Toast notifications: like when the website and a small notificatin pops up to subscribe to newsletter
2. A button to subscribe to newsletter on the navbar

**Comment by hollermay** [comment]
then I would either create a section for this in the landing page or a separate page for this.

**Comment by dakshsinghrathore** [comment]
Toast notification sounds good !👍🏽

**Comment by dakshsinghrathore** [comment]
@hollermay any updates ??

**Comment by hollermay** [comment]
Yeah, the updates are I've designed the bar but I have to integrate that into the homepage and work on php coding or api integration

**Comment by hollermay** [comment]
I will do this by tomorrow night as I have to prepare for some events here

**Comment by hollermay** [comment]
@dakshsinghrathore  I have completed the issue please review and merge. Thanks

**Comment by hollermay** [comment]
@dakshsinghrathore
