### ISSUE TITLE
[FEAT]: Create forms for the respective issue buttons

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#3]
Add respective issue forms to every button, it will be easy for the contributor to raise an issue also it will be visually pleasing for the admin to go through the issue hassle free. 👇

![Screenshot 2023-06-23 at 21-22-39 New Issue · dakshsinghrathore_htmltut](https://github.com/roshan1337d/coding-contests-companion/assets/115932772/82936b04-6272-4660-b3e7-38eb5728d6b0)

**Comment by Soumya-9641** [comment]
I want to work on this issue.Can you please assign it to me?

**Comment by dakshsinghrathore** [comment]
assigned !

**Comment by Soumya-9641** [comment]
Can you please tell me in which file this need to be changed?Please elaborate the issue.I faced confusion while implementing

**Comment by dakshsinghrathore** [comment]
Yeah, sure ! you need to add the respective yaml files for each of the respective issue buttons in the .github/ISSUE_TEMPLATES folder, check this out 👇🏽
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by Soumya-9641** [comment]
ok now I understand little bit.Need more research about that.Thank You @dakshsinghrathore

**Comment by dakshsinghrathore** [comment]
@Soumya-9641 any updates ??

**Comment by Soumya-9641** [comment]
yah.almost done 2 forms are already created one is left.Give me some time.I will complete it.
