### ISSUE TITLE
Updates link in the menu 

### ISSUE THREAD

**Issue by RichaBanerjee** [dakshsinghrathore/ISRO-web#30]
The updates button in the main menu is non-functional. As of now, it simply redirects you to the main landing page of the website. A new page can be created for the updates and linked to the button.

**Comment by dakshsinghrathore** [comment]
@RichaBanerjee Thank you for expressing your interest in the project. Could you please provide more details on how your workflow will enable the desired changes to be implemented?

**Comment by pankaj-2503** [comment]
I want to work on this issue please assign it to me .

**Comment by pankaj-2503** [comment]
I would like to change the color of links on hover .

**Comment by dakshsinghrathore** [comment]
@pankaj-2503 Thanks for showing interest in the project ! Kindly raise a feature request by creating a new issue and then lets discuss what changes you have to offer !

**Comment by RichaBanerjee** [comment]
> @RichaBanerjee Thank you for expressing your interest in the project. Could you please provide more details on how your workflow will enable the desired changes to be implemented?

Yeah sure! We can create a new page that will display all the updates to the user, and this page will be linked to the update button in the menu bar. So when the button is clicked, user will be redirected to the updates page and get all the required information.

**Comment by dakshsinghrathore** [comment]
assigned !

**Comment by RichaBanerjee** [comment]
> assigned !

Let me know if there is some particular content which you would like to have in the updates page!
