### ISSUE TITLE
Update Upcoming Events and Chandrayaan 3 Status

### ISSUE THREAD

**Issue by Venkateeshh** [dakshsinghrathore/ISRO-web#31]
Looking forward to receiving updates on the upcoming events and the status of Chandrayaan 3. This information is crucial for keeping the community informed about ISRO's exciting developments!

**Comment by dakshsinghrathore** [comment]
@Venkateeshh  Thank you for expressing your interest in the project. Could you please provide more details on how your workflow will enable the desired changes to be implemented?

**Comment by Venkateeshh** [comment]
@dakshsinghrathore  Thank you for your prompt response and willingness to collaborate on this issue. I'm excited about the opportunity to contribute to this project and keep the community informed about ISRO's developments.

To address your query, I plan to update the Chandrayaan 3 status by gathering the latest information available through official channels and trusted sources. Similarly, I'll keep a close eye on updates regarding the upcoming NISAR event, ensuring that the information is accurate and up-to-date.

I'll make sure to adhere to the project's contributing guidelines and code of conduct throughout the process. Looking forward to working together to enhance the content on upcoming events and Chandrayaan 3 status!

**Comment by dakshsinghrathore** [comment]
Assigned !
