### ISSUE TITLE
[FEAT]: Favicon missing 

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#32]
The [live](https://dsr-isrowebapp.netlify.app/) link of this repo lacks favicon, kindly implement ISRO icon as the favicon !

**Comment by harshkushwaha2001** [comment]
hi @dakshsinghrathore i would like to work on this issue, so please assign me.

**Comment by pankaj-2503** [comment]
It is great project i would like to contribute to this project by adding favicon , so please assign it to me as it would be very helpful for me to learn contributing to open source

**Comment by dakshsinghrathore** [comment]
@pankaj-2503 assigned, feel free to ping me if you need any sort of help also kindly go through the contributions guideline
