### ISSUE TITLE
[Features]: Image Gallery

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What is your new idea?

Curate a collection of high-resolution images from both organizations, **categorized** by missions, rockets, and facilities.

### proof?

A feature screenshots!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### I want to work on this issue

- [X] I want to work on thos issue

**Comment by dakshsinghrathore** [comment]
Interested contributors can take up this issue !!

**Comment by rohits-web03** [comment]
#### I would like to work on the issue #41 
#### Would really appreciate it if you assign me this issue.

**Comment by dakshsinghrathore** [comment]
Assigned !!

**Comment by rohits-web03** [comment]
#### @dakshsinghrathore I have made the necessary changes.It is mobile responsive as well.
#### Here's the demo:

https://github.com/dakshsinghrathore/ISRO-web/assets/132741672/b38b68dc-49a0-47e2-8dea-3fc755dcdc55

#### If this is fine then I will make the pull request.

**Comment by dakshsinghrathore** [comment]
@rohits-web03 Looks great ! Kindly create a PR also a star on this repo and a follow is much appreciated !😀
