### ISSUE TITLE
BUG: Text on main page not visible

### ISSUE THREAD

**Issue by HarshDeep61034** [dakshsinghrathore/ISRO-web#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The text is not visible due to the background image.
Assign this to me! 
I'll fix this.
![Screenshot from 2023-10-10 21-30-44](https://github.com/dakshsinghrathore/ISRO-web/assets/121210012/5e7be983-f34f-4a3c-97e2-bb1dda4abd7c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by pradyumna14** [comment]
Greetings sir,
I would be glad if you could assign me this task.
Thank you
