### ISSUE TITLE
Feat: Add a "about us section"

### ISSUE THREAD

**Issue by pushkar1713** [dakshsinghrathore/ISRO-web#51]
### Describe the feature

I would like to add a about us section in the drop down menu below updates that will provide information to the users about the inspiration and motive behind project. It is a simple feature but I think it would be a really great one.

### Add ScreenShots

Right here at this position marked below in the screenshot :

<img width="1440" alt="Screenshot 2023-10-10 at 10 18 03 PM" src="https://github.com/dakshsinghrathore/ISRO-web/assets/119427920/256be8c0-6bef-4803-9c75-5c271136c96d">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@pushkar1713 sounds great !

**Comment by dakshsinghrathore** [comment]
@pushkar1713 assigned !

**Comment by dakshsinghrathore** [comment]
sure, take your time!!
