### ISSUE TITLE
BUG: In the footer section, the copyright year should be dynamically generated instead of being statically hardcoded.

### ISSUE THREAD

**Issue by gauravsingh1281** [dakshsinghrathore/ISRO-web#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="959" alt="Screenshot 2023-10-11 003537" src="https://github.com/dakshsinghrathore/ISRO-web/assets/85905403/60ca741c-24d5-4cd8-9a10-859a067282b8">

-------------------

@dakshsinghrathore Right now, the copyright year is written manually, which means someone has to change it whenever a new year begins. However, with just a few lines of code in JavaScript, we can make it automatic. This means that the copyright year will always be up-to-date without anyone having to change it manually. For example, if the current year is 2023, the copyright section will show 2023. And when the year changes to 2024, the copyright section will automatically update to 2024.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@gauravsingh1281 assigned!
