### ISSUE TITLE
Feat: Trivia and Quizzes

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#55]
### Describe the feature

Create interactive quizzes and trivia games to test users' knowledge about ISRO and SpaceX, with rewards for top scorers.

### Add ScreenShots

![Screenshot 2023-10-11 at 11-41-00 Indian Space Research Organisation](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/ea9dd3f9-7d36-484d-99b4-c62970618e29)

Just below the updates create a button for quiz and trivia !

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/c62bbe13-56e9-4ff1-b6bc-2e48303b0f77)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by tharanithar-r** [comment]
Hello. I am interested in working on this feature. Kindly assign it to me.

**Comment by dakshsinghrathore** [comment]
@tharanithar-r assigned !

**Comment by dakshsinghrathore** [comment]
@tharanithar-r any updates?

**Comment by tharanithar-r** [comment]
I am working on bro. I will update ASAP.
