### ISSUE TITLE
BUG: UI glitch

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Fix the UI glitch with hamburger button 

[screen-recorder-wed-oct-11-2023-11-59-57.webm](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/1b61beb9-2933-488b-9c67-ec75b548ee3a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by shohan2001** [comment]
Can you assign this to me?

**Comment by dipak-01** [comment]
@shohan2001 should I solve this issue If you are not available.

**Comment by shohan2001** [comment]
@dipak-01 working on it.

**Comment by dakshsinghrathore** [comment]
@shohan2001 any updates ??

**Comment by dipak-01** [comment]
@dakshsinghrathore  I would love to take this issue, If @shohan2001 is busy or not available.

**Comment by dakshsinghrathore** [comment]
@dipak-01 You can work on this issue !

**Comment by dipak-01** [comment]
@dakshsinghrathore you can check PR #106 for this Issue.
