### ISSUE TITLE
Feat: Add Instagram link

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#58]
### Describe the feature

Add ISRO official Instagram[ link](https://www.instagram.com/isro.dos/) in the footer section !

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/b347ebad-5f75-42db-81d7-d7527d4986f8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by shohan2001** [comment]
Can you assign this to me?

**Comment by AdriaGual** [comment]
Here's the PR: https://github.com/dakshsinghrathore/ISRO-web/pull/59

**Comment by abhi5hek001** [comment]
Could you please assign this task to me!
As I can easily add instagram link :)

**Comment by dakshsinghrathore** [comment]
@shohan2001 Kindly star the repo, and a follow would mean alot ! 
assigning it to you !!

**Comment by shohan2001** [comment]
@dakshsinghrathore  Can you please merge the pr, after that I will be working on the bug assigned to me.
