### ISSUE TITLE
BUG: arrow in not in the middle of main page

### ISSUE THREAD

**Issue by Iamdivyak** [dakshsinghrathore/ISRO-web#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/102896170/445f330e-2aab-491f-80fc-bde9594f0dcf)

the arrow on the main page is not aligned with the horizontal middle.

I want to work on it. kindly assign it to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
Thanks @Iamdivyak for pointing out the bug, I think the issue can be resolved by just adjusting the responsiveness !
am assigning the issue to you !
