### ISSUE TITLE
DOC: wanted to change the description in the PSLV page

### ISSUE THREAD

**Issue by rajibsalui** [dakshsinghrathore/ISRO-web#69]
### What's wrong with the existing documentation

the description provided in the pslv page is of one line and not very specific .So it needs to be changed

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by rajibsalui** [comment]
this needs to be changed

![Screenshot (98)](https://github.com/dakshsinghrathore/ISRO-web/assets/110877754/7882a4f0-c6e3-4d46-b8d4-84cdeb8fdcab)

**Comment by dakshsinghrathore** [comment]
Assigned
