### ISSUE TITLE
Navbar Fixing + UI modifications

### ISSUE THREAD

**Issue by Smitkhobragade** [dakshsinghrathore/ISRO-web#7]
While Scrolling the content basically goes ans gets stuck into navbar and nothing is visible.
![image](https://github.com/dakshsinghrathore/ISRO-web/assets/100017129/001eca34-f52e-421d-9af2-e66a1e534dc0)

also we add some components to it.so that it will be crearly visible rather than having only the background images and text.

so pls assign this issue to me.

**Comment by dakshsinghrathore** [comment]
Assigned👍🏽

**Comment by dakshsinghrathore** [comment]
@Smitkhobragade any updates ??

**Comment by Smitkhobragade** [comment]
Yes Just in completion

**Comment by Smitkhobragade** [comment]
I have generated a PR you can have a look at PR section @dakshsinghrathore
