### ISSUE TITLE
Feat: Linking Satellite names to Official ISRO Docs

### ISSUE THREAD

**Issue by C0dewordSky** [dakshsinghrathore/ISRO-web#70]
### Describe the feature

Linking satellite names to the official Docs would enhance it as it will directly lead the viewer to official ISRO website explaining about that particular satellite.

### Add ScreenShots

![Screenshot 2023-10-12 180541](https://github.com/dakshsinghrathore/ISRO-web/assets/116152057/6882bf46-6455-4c81-90cf-5a45dfa832e7)

![Screenshot 2023-10-12 180723](https://github.com/dakshsinghrathore/ISRO-web/assets/116152057/8c81b528-a7b4-4982-816e-ee8de0f64c8b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@C0dewordSky assigned !!

**Comment by C0dewordSky** [comment]
Hi @dakshsinghrathore , I've fixed the issue and raised a PR, Please have a look and let me know if any enhancements has to be made. Thank you.

**Comment by C0dewordSky** [comment]
For sure @dakshsinghrathore, I've already stared the repo and I'll follow you as well . And Yes I've created a fresh Pr and resolved the conflicts, Please do check it and merge it and add the hacktoberfest-accepted tag. Thank you
