### ISSUE TITLE
Feat: The pages which can be visited through navbar links 

### ISSUE THREAD

**Issue by dipak-01** [dakshsinghrathore/ISRO-web#79]
### Describe the feature

The pages which can be visited through navbar links doesn't have the secondary navbar (hamburger), If you want to add   secondary navbar to all the pages, you can assign it to me., I would love to contribute.

### Add ScreenShots

![Screenshot 2023-10-12 234106](https://github.com/dakshsinghrathore/ISRO-web/assets/120103598/ce51b2db-5872-42c7-abcd-61c9ded2dec4)
![Screenshot 2023-10-12 234100](https://github.com/dakshsinghrathore/ISRO-web/assets/120103598/75c043af-b4ff-4e5f-9599-5cf7c5527eb6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@dipak-01 assigned !

**Comment by dipak-01** [comment]
Resolved
