### ISSUE TITLE
[Feat]: adding menu icon

### ISSUE THREAD

**Issue by ankushtripathii** [dakshsinghrathore/ISRO-web#8]
Hi @dakshsinghrathore I want to add this menu feature that includes [mission, career, update, launches ], could you assign this to me?

![Screenshot 2023-10-03 010444](https://github.com/dakshsinghrathore/ISRO-web/assets/89534251/21a1ad43-fb91-4752-ab64-9331e2816519)

**Comment by dakshsinghrathore** [comment]
assigned 🤝
