### ISSUE TITLE
BUG: the favicon icon only appears in main page.

### ISSUE THREAD

**Issue by Iamdivyak** [dakshsinghrathore/ISRO-web#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when we go to any other page, the favicon icon does not show.
<img width="709" alt="image" src="https://github.com/dakshsinghrathore/ISRO-web/assets/102896170/fdef8820-f74d-4fea-a228-69e8d69a6351">

I want to work on this issue. kindly assign

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
Thanks for pointing out the bug @Iamdivyak am assigning it to you !
