### ISSUE TITLE
refactor the repetitive code

### ISSUE THREAD

**Issue by Iamdivyak** [dakshsinghrathore/ISRO-web#83]
hey @dakshsinghrathore while going throw your codes in index.html. I saw that the div with the class name scroll-arrow (the arrow div) is written twice in all sections. it will work as it is, after removing that repetitive code.

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/102896170/728f6439-3086-45b2-8dfc-37d4c44836d0)

_Originally posted by @Iamdivyak in https://github.com/dakshsinghrathore/ISRO-web/issues/80#issuecomment-1760227985_

**Comment by dakshsinghrathore** [comment]
@Iamdivyak assigned !
