### ISSUE TITLE
Feat: enhance footer section

### ISSUE THREAD

**Issue by Iamdivyak** [dakshsinghrathore/ISRO-web#86]
### Describe the feature

- add more links like the official Instagram and Facebook handle
- add copywrite in the bottom-most part of the webpage

I want to work on this. kindly assign

### Add ScreenShots

-something like this. 
<img width="412" alt="image" src="https://github.com/dakshsinghrathore/ISRO-web/assets/102896170/4bb23b7b-f256-4a08-b807-323bda34e537">
Of course, the text will be according to the website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
Looks good, assigning it to you, kindly keep in mind that the design flow should not be hampered !! @Iamdivyak
