### ISSUE TITLE
BUG: remove a page in Careers tab

### ISSUE THREAD

**Issue by rajibsalui** [dakshsinghrathore/ISRO-web#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want remove this page which is unnecessary. pls assign this to me

![Screenshot (100)](https://github.com/dakshsinghrathore/ISRO-web/assets/110877754/2e018e19-3d1e-487d-b242-d9116a011a3f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@rajibsalui assigned !!
