### ISSUE TITLE
feat: the rewatch button should be reactive

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#9]
The rewatch button on every page should open up a the yt link of the respective launches in the **same page**

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/810b3e54-3977-44b2-ab56-fd84dc8a32d5)

**Comment by ayushsgithub** [comment]
@dakshsinghrathore Bro, the whole webpage is needed to be responsive, it requires a lot of responsiveness for a better user experience
![Screenshot 2023-10-03 130527](https://github.com/dakshsinghrathore/ISRO-web/assets/120788538/a53451c9-a0db-4617-a601-ed0c85876199)

**Comment by dakshsinghrathore** [comment]
@ayushsgithub thanks for pointing it out, but there's already contributor working on responsiveness!
