### ISSUE TITLE
BUG: Page not found and wrong heading

### ISSUE THREAD

**Issue by rohits-web03** [dakshsinghrathore/ISRO-web#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#### Here:
&nbsp;
![Screenshot 2023-10-16 043917](https://github.com/dakshsinghrathore/ISRO-web/assets/132741672/22a065a8-c4f1-4e86-af0e-b7ca88e98129)
![Screenshot 2023-10-16 043939](https://github.com/dakshsinghrathore/ISRO-web/assets/132741672/2a053323-87a9-4f5a-b05e-3c8855785370)
&nbsp;
#### Here:
&nbsp;
![Screenshot 2023-10-16 044014](https://github.com/dakshsinghrathore/ISRO-web/assets/132741672/083fea66-d8cc-42da-b3b4-4ee1edd5e41f)
&nbsp; 
### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@rohits-web03 assigned !!
