### ISSUE TITLE
BUG: Logo isn't Showing in the ISRO Privacy page

### ISSUE THREAD

**Issue by C0dewordSky** [dakshsinghrathore/ISRO-web#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Logo of ISRO isn't showing up in the privacy which makes it look a bit off. It needs to be fixed.

![Screenshot 2023-10-16 190821](https://github.com/dakshsinghrathore/ISRO-web/assets/116152057/1c836976-64e9-4cb9-a6b6-9bd806fb27bb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@C0dewordSky Thanks for choosing this repo to contribute kindly drop a star, assigning the issue to you !
