### ISSUE TITLE
Feat: The Logo in the Privacy page should lead to Official homepage of ISRO.

### ISSUE THREAD

**Issue by C0dewordSky** [dakshsinghrathore/ISRO-web#95]
### Describe the feature

I think the logo in the privacy page should lead to the official ISRO homepage. By providing a link that can be done.  What's your take?

### Add ScreenShots

![Screenshot 2023-10-16 192907](https://github.com/dakshsinghrathore/ISRO-web/assets/116152057/55d90abd-1b03-45b4-b381-766aba2633ac)

![Screenshot 2023-10-16 193200](https://github.com/dakshsinghrathore/ISRO-web/assets/116152057/ed798b7b-d5ea-464a-864e-99ed07c36804)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
assigned !!
