### ISSUE TITLE
BUG: Menu Icon Overlaps Navigation Bar Items on Small Screens

### ISSUE THREAD

**Issue by jaitensahu** [dakshsinghrathore/ISRO-web#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On smaller screens, such as mobile devices or narrow viewports, a user interface issue has been identified. When the website is viewed on these smaller screens, the menu icon overlaps with the navigation bar items, resulting in a suboptimal user experience.

Steps to Reproduce:

1. Access the website on a mobile device or resize the browser window to a smaller viewport.
2. Observe the navigation bar, particularly the menu icon and navigation items.
3. Note that the menu icon appears to overlap with the navigation items, potentially causing issues with user interaction and readability.

https://github.com/dakshsinghrathore/ISRO-web/assets/127736781/f79f78d1-f1ee-43c5-957a-9760bc472356

Expected Behavior

1. On larger screens, the navigation bar should display all individual navigation tab items, providing users with direct access to various sections of the website.

2. On smaller screens, such as mobile devices or narrow viewports, the navigation bar should adapt to a more space-efficient design. In this responsive design, all individual navigation tab items should be merged into a collapsible menu (commonly represented by a menu icon or "hamburger" icon).

3. When the user interacts with the menu icon on smaller screens, the collapsible menu should expand to display the full list of navigation items, ensuring a seamless and user-friendly navigation experience.

4. The responsive design should prioritize readability, ease of use, and a visually appealing layout to accommodate limited 
    screen real estate while maintaining the website's functionality.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a Hacktoberfest'23 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@jaitensahu Thanks for finding out the bug ! kindly star the repo and a follow will be highly appreciated ! 🙌🏽😀

**Comment by jaitensahu** [comment]
hi @dakshsinghrathore Already followed you and starred the repo
